image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy
  - sonar

variables:
  project: "EasyMechBackend"
  repo: "easymech-backend"
  SONARSCANNER: “C:\\GitLab-Runner\\gitlab-runner.exe”

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass
  - "dotnet restore"
  
sonar:
  stage: sonar
  script:
    - chcp 65001
    - Scripts\\sonar_run.bat
  only:
    - develop
  tags:
    - epj

build:
  stage: build
  variables:
    build_path: "$project/"
  script:
    - "cd $build_path"
    - "dotnet build"

test:
  stage: test
  script:
    - dotnet test

deploy_stage:
  stage: deploy
  environment: Staging
  only:
    - master
  script:
    - cd ..
    - ls
    - sshpass -V
    - export SSHPASS=$USER_PASS 
    - sshpass -e ssh -o stricthostkeychecking=no gitlab@sinv-56057.edu.hsr.ch date
    - sshpass -e ssh -o stricthostkeychecking=no gitlab@sinv-56057.edu.hsr.ch "sudo /app/scripts/docker-cleanup.sh 40006 easymech-backend"
    - sshpass -e scp -o stricthostkeychecking=no -r $repo/ gitlab@sinv-56057.edu.hsr.ch:/app/docker
    - sshpass -e ssh -o stricthostkeychecking=no gitlab@sinv-56057.edu.hsr.ch "sudo /app/scripts/docker-backend.sh 40006 easymech-backend"
